create table if not exists mix_designs (
  user_id text not null,
  grade text not null,
  r_san numeric,
  c_san numeric,
  mm20 numeric,
  mm10 numeric,
  cem1 numeric,
  fly_ash numeric,
  water numeric,
  admix1 numeric,
  admix2 numeric,
  primary key (user_id, grade)
);

create table if not exists entry_current (
  user_id text not null,
  id integer not null,
  docket_no text,
  customer_name text,
  site text,
  grade text,
  qty text,
  truck_driver text,
  truck_number text,
  batch_start text,
  batch_stop text,
  primary key (user_id, id)
);

create table if not exists batch_history (
  id bigint generated by default as identity primary key,
  created_at timestamptz default now(),
  user_id text not null,
  docket_no text,
  customer_name text,
  site text,
  grade text,
  qty text,
  truck_driver text,
  truck_number text,
  batch_start text,
  batch_stop text,
  mix_design jsonb,
  report_rows jsonb,
  totals jsonb
);
